model Connected_Godley_table 
Modelica.Blocks.Interfaces.RealOutput BC(start = 0);
Modelica.Blocks.Interfaces.RealOutput BPL(start = 0);
Modelica.Blocks.Interfaces.RealOutput FL(start = 0);
Modelica.Blocks.Interfaces.RealOutput FD(start = 0);
Modelica.Blocks.Interfaces.RealOutput WD(start = 0);
Modelica.Blocks.Interfaces.RealOutput N(start = 300);
Modelica.Blocks.Interfaces.RealOutput a(start = 1);
Modelica.Blocks.Interfaces.RealOutput Kr(start = 900);
Modelica.Blocks.Interfaces.RealOutput PC(start = 1.25);
Modelica.Blocks.Interfaces.RealOutput W(start = 1);
Modelica.Blocks.Interfaces.RealOutput λ(start = 0);
Modelica.Blocks.Interfaces.RealInput ode_Kr;
Modelica.Blocks.Interfaces.RealInput I;
Modelica.Blocks.Interfaces.RealInput H;
Modelica.Blocks.Interfaces.RealInput B;
Modelica.Blocks.Interfaces.RealInput ode_W;
Modelica.Blocks.Interfaces.RealInput ode_a;
Modelica.Blocks.Interfaces.RealInput G;
Modelica.Blocks.Interfaces.RealInput C;
Modelica.Blocks.Interfaces.RealInput D;
Modelica.Blocks.Interfaces.RealInput ode_N;
Modelica.Blocks.Interfaces.RealInput J;
Modelica.Blocks.Interfaces.RealInput ode_PC;
Modelica.Blocks.Interfaces.RealInput E;
Modelica.Blocks.Interfaces.RealInput ode_λ;
Modelica.Blocks.Interfaces.RealInput A;
Modelica.Blocks.Interfaces.RealInput F;
equation 
der(BC) = (I) + (-J); 
der(BPL) = (B) + (-E) + (-F) + (-G); 
der(FL) = (A) + (-B) + (C) + (-I) + (J); 
der(FD) = (-B) + (C) + (-D) + (E) + (G) + (H) + (-I) + (J); 
der(WD) = (D) + (F) + (-H); 
der(N) = (ode_N); 
der(a) = (ode_a); 
der(Kr) = (ode_Kr); 
der(PC) = (ode_PC); 
der(W) = (ode_W); 
der(λ) = (ode_λ); 
end Connected_Godley_table; 
