model Godley_table 
output Real BC(start = 0);
output Real BPL(start = 0);
output Real FL(start = 0);
output Real FD(start = 0);
output Real WD(start = 0);
output Real N(start = 300);
output Real a(start = 1);
output Real Kr(start = 900);
output Real PC(start = 1.25);
output Real W(start = 1);
output Real λ(start = 0);
input Real J;
input Real E;
input Real ode_PC;
input Real C;
input Real F;
input Real H;
input Real A;
input Real ode_N;
input Real ode_W;
input Real ode_λ;
input Real .;
input Real G;
input Real ode_a;
input Real ode_Kr;
input Real D;
input Real I;
input Real B;
equation 
der(BC) = (I) + (-J); 
der(BPL) = (B) + (-E) + (-F) + (-G); 
der(FL) = (A) + (-B) + (C) + (-I) + (J); 
der(FD) = (-B) + (C) + (-D) + (E) + (G) + (H) + (-I) + (J); 
der(WD) = (D) + (F) + (-H); 
der(N) = (ode_N); 
der(a) = (ode_a); 
der(Kr) = (ode_Kr); 
der(PC) = (ode_PC); 
der(W) = (ode_W); 
der(λ) = (ode_λ); 
end godley_table; 
